### ISSUE TITLE
Feature request: automatic filling in user profile details 

### ISSUE THREAD

**Issue by gemguardian** [michael-milette/moodle-local_contact#18]
User Case: 

Susan is a user in Moodle. She filles in the contactform in the Moodle course to ask a question to the administation department. When she fills in the form her name and e-mailaddress - as placed in her profile - are filled in automatically. 

Option: Susan rather has that the reply goes to her private mailadress then the schools, so she alternates the e-mailadress.

**Comment by michael-milette** [comment]
Hi gemguardian,

Thanks for the suggestion. I am actually currently working on a new Moodle filter plugin that that will enable you to include some profile details in the form. I will let you know as soon as the new plugin is ready here on GitHub.

As for having the option to change the reply email address, My initial thoughts are to not allow this as students could then have replies sent to anyone, not just their own email address. It could also make it more difficult for administrators to identify the sender if you have multiple users with the same name. The reason for using the account's email address is because it has been authenticated during the registration process and/or the change email address process so you are sure of who it belongs to.

My suggestion here is that you create a separate field, perhaps called "reply-address" that students could use if they wanted to have the reply go to a different email address. The administrator would then need to modify the reply manually when responding to the email.

The alternative is that you simply tell students to change their email address in their profile if they want emails from Moodle to go to a different email address.

Hope you find this useful and helpful.

**Comment by gemguardian** [comment]
Hi Michael, 

Thank you for responds. 
I actually thought of your option using a sepatate field as well. 

 

Looking forward to include some profile details in the form. 


Gem

 

Van: Michael Milette [mailto:notifications@github.com] 
Verzonden: maandag 3 juli 2017 21:05
Aan: michael-milette/moodle-local_contact <moodle-local_contact@noreply.github.com>
CC: gemguardian <gemma@ltnc.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [michael-milette/moodle-local_contact] Feature requist: automatic filling in user profile details (#18)

 

Hi gemguardian,

Thanks for the suggestion. I am actually currently working on a new Moodle filter plugin that that will enable you to include some profile details in the form. I will let you know as soon as the new plugin is ready here on GitHub.

As for having the option to change the reply email address, My initial thoughts are to not allow this as students could then have replies sent to anyone, not just their own email address. It could also make it more difficult for administrators to identify the sender if you have multiple users with the same name. The reason for using the account's email address is because it has been authenticated during the registration process and/or the change email address process so you are sure of who it belongs to.

My suggestion here is that you create a separate field, perhaps called "reply-address" that students could use if they wanted to have the reply go to a different email address. The administrator would then need to modify the reply manually when responding to the email.

The alternative is that you simply tell students to change their email address in their profile if they want emails from Moodle to go to a different email address.

Hope you find this useful and helpful.

**Comment by michael-milette** [comment]
Hi @gemguardian,

Take a look at my new plugin. You will find it at:

https://github.com/michael-milette/moodle-filter_filtercodes

What other profile details were you looking to fill the form with?

Best regards,

Michael

**Comment by gemguardian** [comment]
Hi Michael,

 

Sorry for the late response. Holiday time 😊

 

I used Generico filter to create the metadata filters. But I really do like the conditional display content filter and the language!

 

I am certainly going to test your plug-in. It’s on my schedule for this week 😊 

 

---

 

For the form; the profile fields would be nice:

*	to use custom profile fields but I know that is probably difficult. 
*	Institute 
*	City
*	Language
*	Country
*	Department

 

Gem

 

 

Van: Michael Milette [mailto:notifications@github.com] 
Verzonden: donderdag 3 augustus 2017 20:39
Aan: michael-milette/moodle-local_contact <moodle-local_contact@noreply.github.com>
CC: gemguardian <gemma@ltnc.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [michael-milette/moodle-local_contact] Feature request: automatic filling in user profile details (#18)

 

Hi @gemguardian <https://github.com/gemguardian> ,

Take a look at my new plugin. You will find it at:

https://github.com/michael-milette/moodle-filter_filtercodes

What other profile details were you looking to fill the form with?

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @gemguardian ,

Feel free to use Generico together with the conditional tags in FilterCodes. They should work well together.

Best regards,

Michael
