### ISSUE TITLE
Can't save form

### ISSUE THREAD

**Issue by jubaier** [michael-milette/moodle-local_contact#19]
Hello Michael,

I still can not insert the contact form.

I inserted the sample code into a text block (in html mode). When I try to save in html mode nothing happens (no saving). When I try to save in regular mode I also can not save because the "required fields" are empty. When I insert a value and try to save it says "wrong session key".

I tried with chrome, firefox and ie. It does not work.

What am I doing wrong?

**Comment by michael-milette** [comment]
Hi @jubaier,

So if I understand you correctly, you did the following:
1. Added a block to your page.
2. Configured the block.
3. In the Content field, you switched to source code view
4. Then paste in your form.
5. You then clicked the "Save Changes" button.

If that is when you get the error message, there may be a problem with your installation of Moodle. Repeat the same process using the source code for the [Minimal Template Form example](https://github.com/michael-milette/moodle-local_contact/wiki/HTML-Form-Templates#minimal-template-form-for-contact-form-for-moodle). If this is still happening, I suspect that you will have the same problem no matter what content you add to the HTML block, even if it is not a form.

Based on the error message you provided regarding the missing session key, I may have misunderstood your explanation of the error. If you are actually able to save the form in the HTML block but are getting that error message when you submit the form, that is a completely different story. In that case, you probably didn't include the SCRIPT tag in the form. This is necessary in order for Moodle to insert the session key into the hidden field in the form. Read the documentation and examine the code included in the example mentioned above. There are specific elements that must be part of the form in order for it to work. These are part of the anti-spam security built into the Contact Form plugin.

Last but not least, don't forget to turn debugging off once you have resolved the issue as the debug error messages are not meant for the public. Errors in Moodle could reveal confidential security information about your website under some circumstances.

Hope something in all of this helps. Let me know how it turns out.

**Comment by michael-milette** [comment]
Hi @jubaier,

I just thought of another possibility. The sample code included in the documentation for the Contact Form for Moodle plugin assumes that you are submitting the form from a Moodle page. If you are submitting it from a different type of plugin like an HTML block, you may need to modify the URL in the ACTION parameter of the FORM tag so that it reflects the location of local/contact/index.php plugin. In the future, we will be able to work around this through the use of a new upcoming filter_filtercodes plugin.

**Comment by jubaier** [comment]
Hi Michael,

thank you for your fast reply.

I tried the Minimal Template Form Example, tried to use the form on a Moodle page, changed the URL in the ACTION parameter, did a reinstall of your plugin. That all did not work.

When I insert the sample code in source code view it might delete the form tags. Could this cause the problem?

I am going to check my Moodle installation now.
Hope to find the problem.

**Comment by michael-milette** [comment]
What version of Moodle are you using? Are you using the default Atto editor in Moodle or some other one (like TinyMCE)?

I remember TinyMCE used to filter out FORM tags at one point unless you overrode its configuration settings however I have not had that happen to me with Atto.

Also, what language are you using Moodle in? I have noticed some bugs in Moodle 3.3 and the Boost theme when trying to save some settings using non-English languages.

**Comment by jubaier** [comment]
I am using Moodle 3.2.2 in German and the default Atto editor.

I also installed Atto Styles Plugin. Could this cause the problem?

**Comment by michael-milette** [comment]
Not sure. I've never tried the Atto Styles plugin. Can you try uninstalling it?

**Comment by jubaier** [comment]
I uninstalled Atto Styles. Still not working :(

**Comment by michael-milette** [comment]
Are you able to save content at all in the block? Even if it doesn't contain a form?

**Comment by jubaier** [comment]
I can save everything, but not the form.

**Comment by michael-milette** [comment]
Hi @jubaier ,

Sorry, I've been away for a few weeks. Did you manage to resolve the issue? If not, let me know and I will see what more can be done.
