### ISSUE TITLE
Add Option to Send from Users Mail Address

### ISSUE THREAD

**Issue by jezhops** [michael-milette/moodle-local_contact#40]
Currently emails are sent from noreply@yourmoodlesite.edu

This is an issue for us as we want emails routed directly into a helpdesk system where they are automatically converted into a "call".

This system only accepts valid mail addresses on the University domain and in addition to creating the ticket sends users an email with their ticket details.

What we would like to add is an additional admin setting:

- Setting Name: send_from_user_address
- Default Value: False (would continue to send via noreply@yourmoodlesite.edu as is the case currently)

When enabled this would send emails from the users mail address as opposed to the default Moodle address.

We can add this feature and submit a pull request if you would be likely to accept it?

**Comment by michael-milette** [comment]
Unfortunately that is not an option. Your mail server would very likely reject the email. Your server might be configured to allow this however most servers would reject it with an SMTP Relay Error in order to prevent just anyone from using a mail server to send spam. If I did do this, I would be quickly inundated with people reporting that emails could not be delivered.

With that said, I will leave this issue open. When I develop email form processors like this, I usually set the reply-to field so that you can simply click "Reply" in your email client and have the To field automatically set to the originator email address.

Unfortunately it looks like I didn't get around to implementing this yet in Contact Form for Moodle. I will see if it might be possible to get it into the next release, maybe over the Christmas holidays if I have time - otherwise it will end up in the May release.

Once that is in place, it will just be a matter of having your ticket system use the reply-to field instead of the From field.

Best regards,

Michael

**Comment by jezhops** [comment]
Hi Michael,

I am aware this could cause issues with SPF but this would be an option off by default, documentation could explain the caveat and I think in most cases there will only be one or two mail addresses white listed to recieve the emails?

That said, if we can make Reply To work that maybe a better option. As there is already a replyto parameter in email_to_user()

* @param string $replyto Email address to reply to

`function email_to_user($user, $from, $subject, $messagetext, $messagehtml = '', $attachment = '', $attachname = '',    $usetrueaddress = true, $replyto = '', $replytoname = '', $wordwrapwidth = 79) {
`
it would only require a tweak to line 309 of your local_contac.php class to add that paremter to the call:

`$status = email_to_user($to, $from, $subject, html_to_text($htmlmessage), $htmlmessage, '', '', true);`

If it is as easy as that to impement we can look at making that change, if we did would you want that to be the default behaviour or to add an option for it so it is configurable?

If that does not work of us the we will have to go ahead and add the option to change the sender address in spite of the issues you mention, but would rather not fork it if there is a way to contribute changes back and hold everything together in one pugin.

**Comment by michael-milette** [comment]
Hi @jezhops ,

That is exactly where the change was needed. Not sure why I had not included it before. As I mentioned, I usually do when using that particular function. Probably didn't get around to it and forgot. Anyway, the reply-to email address has now been added as of #47. Thanks again for bringing this issue to my attention. Much appreciated.

Michael
