### ISSUE TITLE
Feature Request - File Upload Capability

### ISSUE THREAD

**Issue by merritt75k** [michael-milette/moodle-local_contact#46]
Ability to have a file upload and it email as an attachment.

**Comment by michael-milette** [comment]
Hi Kristin,
Thank you for taking the time to submit this feature request here on GitHub. I will consider including it in a future release of Contact for Moodle.

If you don't mind my asking, what size files are you looking to allow people to upload? Can you give me an example of how you might want people to use this?

Best regards,

Michael

**Comment by merritt75k** [comment]
Not at all! You are so awesome btw!  When working on forms for our Records Office, I have found there will be times an online student may need to attach transcripts or schedules from other institutions. In some cases, students may need to provide proof of ID.

**Comment by michael-milette** [comment]
Thank you Kristin. 👍

**Comment by bfriesenvcc** [comment]
I was thinking the same thing, for support screenshots.

**Comment by stdoma** [comment]
I would also like it if I could include pictures in the messages with a file upload. This can be helpful when generating support tickets in order to save a little communication effort with the user.

**Comment by pejhab** [comment]
I would like to enquire about the implementation of file upload. Has it been implemented? Has it been abandoned?

**Comment by michael-milette** [comment]
Hi @pejhab ,

Adding a file upload option is definitely still on my TODO list however my time is otherwise taken up by client billable time at the moment.

If you are able to submit a pull request for this feature, or you would like to fund its development, please let me know. I would be happy to work with you to get this feature implemented.

Best regards,

Michael

**Comment by andrewrowatt-masseyuni** [comment]
Hi @michael-milette just adding my vote to this request.  I'll also talk to our devs (Catalyst IT) about developing this.

Kind regards,
   Andrew

**Comment by sba-edu** [comment]
Hi all, I'm not an expert on github, but it looks to me like there has been a solution to this feature request since January.
Is there a particular reason why the code proposal has not yet been officially confirmed and adopted?
Is the solution ready for production use, or are there still some concerns?
Is it worth manually adding the proposed code to our Moodle installation, or will it be distributed via the official plugin in the foreseeable future?

**Comment by michael-milette** [comment]
This ability to support an attachment has been added to Contact Form version 1.3.0. Please note that you must enable it in the plugin's settings in order to use it. You will also need to make some changes to the HTML of your form. See the documentation in the plugin's README.md file.

Special thanks go out to @alexmorrisnz for contributing his time and the fruit of his efforts in adding this feature.

Best regards,

Michael
