### ISSUE TITLE
Feature Request: Continue to previous page (was Redirect)

### ISSUE THREAD

**Issue by merritt75k** [michael-milette/moodle-local_contact#47]
Hi Michael! I hope you had a wonderful holiday season!
Question:
In the documentation, it states:

You can also add the referring URL, the page that the user was on before going to the form, by adding the following to your form:
<input type="hidden" id="referrer" name="referrer" value="">
<script>document.getElementById('referrer').value = document.referrer;</script>

I am not getting the result. Is there something I am doing wrong?

**Comment by michael-milette** [comment]
Hi Kristin, Happy New Year!

To get the referring URL, you need both lines:

    <input type="hidden" id="referrer" name="referrer" value="">
    <script>document.getElementById('referrer').value = document.referrer;</script>

To get referrer URL, you also need to be accessing the form from another web page. If you typed in the URL or accessed it through a bookmark/favourite, there would naturally be no referrer URL.

To test it, make sure you go to some other web page first and then click on a link that takes you to the page that has your form. The page you came from will be the referrer URL. The JavaScript snippet simply populates the hidden field with this referrer value.

Hope this helps. Let me know if it still doesn't work for you or you have any questions.

Best regards,

Michael

**Comment by merritt75k** [comment]
Gotcha! I was thinking after I click the continue button it would take me back to the page I started from. My apologies for misunderstanding.

**Comment by michael-milette** [comment]
Hi Kristin,

Sorry, that particular Continue button is set to take you back to the home page at the moment. However modifying it to take you back to the page where you started is a good idea. I will consider it for a future release of the plugin.

This will likely still require the two lines I previously mentioned in your form so, if you make sure they are included in your form today, your issue will likely automatically fix itself when you upgrade the plugin in the future.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi Kristen,

The change has been applied to the [DEV](https://github.com/michael-milette/moodle-local_contact/tree/dev) branch. If you have a chance, let me know how it works out for you. If everything seems ok, I will include this change in the next release of Contact Form around April or May just before Moodle 3.5 LTS comes out.

Best regards,

Michael

**Comment by merritt75k** [comment]
Hi Michael!
It is not taking back to the specific page the form was on, however it takes me back to the original course which is just fine for my needs.
Thanks so much! As always, YOU ROCK!!!

**Comment by michael-milette** [comment]
You are welcome Kristin. Glad it was something that I could do quickly.

If you want to be returned to the form that you just submitted, use **document.location.href** instead of 
**document.referrer**. So the two lines would become:

    <input type="hidden" id="referrer" name="referrer" value="">
    <script>document.getElementById('referrer').value = document.location.href;</script>

You will still need to be using the latest DEV script for it to work until the next version is released in a few months.

Note that this will result in the form address being inserted into the email in the referrer field instead of the page from where they actually came from before the form which can be a little misleading.

For a support page, I personally prefer to use **document.referrer** in order to submit the URL of the page from where they came so that I know what they are talking about when they say something like "Lesson 2 of the course didn't work" but offer you no clue which course they were in at the time.

Returning the student back to the page they were on before the form was submitted is also useful if it was rather complicated to navigate back to where they were before they submitted the form. This is especially important if you are dealing with students who may have accessibility issues.

Best regards,

Michael
