### ISSUE TITLE
Just want to show a link, not a block, on the front page

### ISSUE THREAD

**Issue by wallyreport** [michael-milette/moodle-local_contact#57]
I am not sure if this is a feature request. Maybe this can already be done? 

On the front page, I do not want to show the entire form, just a link that will take somebody to the form. 

I tried saving the sample "contact us" form as a static page, but that does not work. I can link to it, but it will not accept input.

**Comment by michael-milette** [comment]
Hi @wallyreport ,

As you already indicated, you will need to create a page. Assuming you have not enabled "Force users to log in", I recommend this approach which will create a link to the front page called **Contact us**. When someone clicks on it, they will be taken to that page on your site:

1. Login as a Moodle administrator.
2. Go to your Front Page.
3. Turn editing on.
4. Add a **Page** type activity/resource and call it **Contact us**.
5. For the content of the page, insert your HTML form or related FilterCode (if you are using it) and save.

Note: If you are using Filter Codes, make sure it is Enabled for content in Moodle's Manage Filter settings. If you are not using FilterCodes, be sure to check and replace any reference to {wwwroot} in your form with the URL to your site's webroot.

If you don't like where the link was placed, copy the link and use CSS to hide it. You may also want to hide the link in the Nav Drawer if you don't want it to appear there either. You can then create a link to your contact form wherever you want.

TIP: If you are uisng the local_staticpage plugin, be sure to enable "processfilters" (if using FilterCodes) and disabled "cleanhtml" in its settings. Otherwise it will not process FilterCodes or StaticPage may delete or filter out the HTML code of your form.

If you want more help with this, please share a link to your **Contact us** page. If you do not want to share it publicly, feel free to send it to me through my website at https://www.tngconsulting.ca/contact

Should you require more help, feel free to re-open this ticket.

Best regards,

Michael
